version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile-frontend
    ports:
      - "80:80"
    container_name: hotstar-frontend

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile-backend
    ports:
      - "3000:3000"
    container_name: hotstar-backend
